const PDFDocument = require('pdfkit');
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, BorderStyle, ShadingType, AlignmentType,
  VerticalAlign, Header, Footer, PageNumber
} = require('docx');
const PersonalDetails = require('../models/PersonalDetails');

const PROFILE_PROJECTION = {
  full_name: 1, date_of_birth: 1, email: 1, phone_number: 1, address: 1
};

const ALLOWED_TYPES = ['pdf', 'docx'];

function buildProfileRows(profile) {
  const dob = profile.date_of_birth
    ? new Date(profile.date_of_birth).toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })
    : 'N/A';

  return [
    ['Full Name',     profile.full_name    || 'N/A'],
    ['Date of Birth', dob],
    ['Email Address', profile.email        || 'N/A'],
    ['Mobile Number', profile.phone_number || 'N/A'],
    ['Address',       profile.address      || 'N/A']
  ];
}

async function sendDocument(res, profile, type) {
  const rows = buildProfileRows(profile);
  const genDate = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });

  if (type === 'pdf') {
    const doc = new PDFDocument({ margin: 0, size: 'A4', compress: true });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="personal-details.pdf"');
    doc.pipe(res);

    const W        = doc.page.width;
    const H        = doc.page.height;
    const MARGIN   = 50;
    const CONTENT  = W - MARGIN * 2;
    const PRIMARY  = '#1565C0';
    const ACCENT   = '#E3F2FD';
    const DARK     = '#1A2B3C';
    const GRAY     = '#607080';
    const DIVIDER  = '#CFD8DC';
    const ROW_ALT  = '#F7FAFC';
    const BANNER_H = 130;
    const genTime  = new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });

    doc.rect(0, 0, W, BANNER_H).fill(PRIMARY);

    for (let i = 0; i < 6; i++) {
      doc.rect(W - 10 - i * 18, 0, 10, BANNER_H).fillOpacity(0.06).fill('white');
    }
    doc.fillOpacity(1);

    doc.rect(0, BANNER_H, W, 5).fill('#0D47A1');

    const BANNER_LABEL = '#D6E8FF';
    const BANNER_MUTED = '#B3D4FC';

    doc.fillColor(BANNER_LABEL).fontSize(8.5).font('Helvetica')
       .text('FULL STACK ASSESSMENT  ·  PROFILE DOCUMENT', MARGIN, 22, { width: 340 });

    doc.fillColor('#FFFFFF').fontSize(30).font('Helvetica-Bold')
       .text('Profile Details Report', MARGIN, 42, { width: 360, lineGap: 0 });

    doc.fillColor(BANNER_LABEL).fontSize(10).font('Helvetica')
       .text('Official Personal Information Summary', MARGIN, 82, { width: 340 });

    doc.fillColor(BANNER_MUTED).fontSize(7.5).font('Helvetica')
       .text('GENERATED ON', W - MARGIN - 120, 26, { width: 120, align: 'right' });

    doc.fillColor('#FFFFFF').fontSize(11).font('Helvetica-Bold')
       .text(genDate, W - MARGIN - 120, 40, { width: 120, align: 'right' });

    doc.fillColor(BANNER_LABEL).fontSize(9).font('Helvetica')
       .text(genTime, W - MARGIN - 120, 57, { width: 120, align: 'right' });

    doc.rect(W - MARGIN - 135, 22, 0.5, 60).fillOpacity(0.3).fill('#FFFFFF');
    doc.fillOpacity(1);

    let y = BANNER_H + 28;
    doc.rect(MARGIN, y, 4, 20).fill(PRIMARY);
    doc.fillColor(DARK).fontSize(11).font('Helvetica-Bold')
       .text('PERSONAL INFORMATION', MARGIN + 14, y + 4, { characterSpacing: 0.5 });

    y += 36;

    const COL1 = 160;
    const COL2 = CONTENT - COL1;
    const ROW_H = 36;

    doc.rect(MARGIN, y, CONTENT, ROW_H * rows.length).lineWidth(0.5).strokeColor(DIVIDER).stroke();

    rows.forEach(([label, value], i) => {
      const rowY = y + i * ROW_H;
      const isAlt = i % 2 === 1;

      if (isAlt) doc.rect(MARGIN, rowY, CONTENT, ROW_H).fill(ROW_ALT);
      doc.rect(MARGIN, rowY, COL1, ROW_H).fill(isAlt ? '#EEF4FB' : ACCENT);
      doc.rect(MARGIN + COL1, rowY, 0.5, ROW_H).fill(DIVIDER);
      if (i > 0) doc.rect(MARGIN, rowY, CONTENT, 0.5).fill(DIVIDER);

      doc.fillColor(PRIMARY).fontSize(9.5).font('Helvetica-Bold')
         .text(label.toUpperCase(), MARGIN + 12, rowY + ROW_H / 2 - 6, { width: COL1 - 16 });

      doc.fillColor(DARK).fontSize(10.5).font('Helvetica')
         .text(value, MARGIN + COL1 + 14, rowY + ROW_H / 2 - 6, { width: COL2 - 20, lineGap: 0 });
    });

    y += ROW_H * rows.length + 30;
    doc.rect(MARGIN, y, CONTENT, 0.5).fill(DIVIDER);

    const footerY = H - 45;
    doc.rect(0, footerY - 6, W, 51).fill('#F4F7FA');
    doc.rect(0, footerY - 6, W, 1).fill(DIVIDER);

    doc.fillColor(GRAY).fontSize(8).font('Helvetica')
       .text('Generated by Full Stack Assessment App  ·  This is a system-generated document.',
             MARGIN, footerY + 6, { width: CONTENT, align: 'center' });

    doc.fillColor(GRAY).fontSize(8)
       .text('Page 1 of 1', MARGIN, footerY + 18, { width: CONTENT, align: 'center' });

    doc.end();
    return;
  }

  const BLUE       = '1565C0';
  const LIGHT_BLUE = 'E3F2FD';
  const DARK       = '0D2137';
  const ALT_BG     = 'F7FAFC';
  const LABEL_ALT  = 'EEF4FB';

  const thinBorder = (color = 'CFD8DC') => ({
    top:    { style: BorderStyle.SINGLE, size: 1, color },
    bottom: { style: BorderStyle.SINGLE, size: 1, color },
    left:   { style: BorderStyle.SINGLE, size: 1, color },
    right:  { style: BorderStyle.SINGLE, size: 1, color }
  });

  const tableRows = rows.map(([label, value], i) => {
    const isAlt = i % 2 === 1;
    return new TableRow({
      children: [
        new TableCell({
          width: { size: 30, type: WidthType.PERCENTAGE },
          verticalAlign: VerticalAlign.CENTER,
          shading: { type: ShadingType.CLEAR, fill: isAlt ? LABEL_ALT : LIGHT_BLUE },
          borders: thinBorder(),
          margins: { top: 80, bottom: 80, left: 120, right: 80 },
          children: [new Paragraph({
            children: [new TextRun({ text: label, bold: true, color: BLUE, size: 20 })]
          })]
        }),
        new TableCell({
          width: { size: 70, type: WidthType.PERCENTAGE },
          verticalAlign: VerticalAlign.CENTER,
          shading: { type: ShadingType.CLEAR, fill: isAlt ? ALT_BG : 'FFFFFF' },
          borders: thinBorder(),
          margins: { top: 80, bottom: 80, left: 120, right: 80 },
          children: [new Paragraph({
            children: [new TextRun({ text: value, color: DARK, size: 20 })]
          })]
        })
      ]
    });
  });

  const docx = new Document({
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 22 }
        }
      }
    },
    sections: [{
      headers: {
        default: new Header({
          children: [
            new Paragraph({
              alignment: AlignmentType.RIGHT,
              children: [new TextRun({ text: `Generated: ${genDate}`, color: '607080', size: 16 })]
            })
          ]
        })
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: 'Generated by Full Stack Assessment App  ·  Page ', color: '607080', size: 16 }),
                new TextRun({ children: [PageNumber.CURRENT], color: '607080', size: 16 }),
                new TextRun({ text: ' of ', color: '607080', size: 16 }),
                new TextRun({ children: [PageNumber.TOTAL_PAGES], color: '607080', size: 16 })
              ]
            })
          ]
        })
      },
      children: [
        new Paragraph({
          alignment: AlignmentType.LEFT,
          spacing: { after: 120 },
          children: [
            new TextRun({ text: 'Profile Details Report', bold: true, color: BLUE, size: 48 })
          ]
        }),
        new Paragraph({
          spacing: { after: 360 },
          children: [
            new TextRun({ text: 'FULL STACK ASSESSMENT  ·  PERSONAL INFORMATION', color: '90A4AE', size: 16, allCaps: true })
          ]
        }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: tableRows
        }),
        new Paragraph({ spacing: { after: 200 }, children: [] })
      ]
    }]
  });

  const buffer = await Packer.toBuffer(docx);
  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
  res.setHeader('Content-Disposition', 'attachment; filename="profile-details.docx"');
  res.send(buffer);
}

exports.generateDocument = async (req, res) => {
  const type = req.params.type?.toLowerCase();

  if (!ALLOWED_TYPES.includes(type)) {
    return res.status(400).json({ error: 0, message: 'Invalid document type. Allowed values: pdf, docx' });
  }

  try {
    const profile = await PersonalDetails.findOne(
      { user_id: req.user.id },
      PROFILE_PROJECTION
    ).lean();

    if (!profile) {
      return res.status(404).json({ error: 0, message: 'Profile not found. Please fill personal details first.' });
    }

    await sendDocument(res, profile, type);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 0, message: `Error generating ${type.toUpperCase()}` });
  }
};
